name: run pandas on machine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pandas-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout-code
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v4

    - name: install dependencies
      run: pip install pandas

    - name: run pandas job
      run: python app.py